{"name": "test_login02", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "self = <scripts.test_login.TestLogin object at 0x00000193C219CE80>\n\n    def test_login02(self):\n>       assert 0\nE       assert 0\n\nscripts\\test_login.py:7: AssertionError"}, "start": 1704817411982, "stop": 1704817411983, "uuid": "c6bc8816-7b61-4b2d-844c-5cc68291b2f9", "historyId": "764a98853e30b65201915112fa730b4f", "testCaseId": "764a98853e30b65201915112fa730b4f", "fullName": "scripts.test_login.TestLogin#test_login02", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "URFWVOQQRLXGHWP"}, {"name": "thread", "value": "13740-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_login"}]}